package com.lilbro.picobotella.data.model

/**
 * Domain model representing a challenge (reto).
 *
 * This class is used both as the ViewModel state object and as the
 * data transferred to / from Firestore.
 *
 * @property id Unique identifier. Auto-generated by Firestore.
 * @property descripcion Text content of the challenge.
 * @property createdAt Unix-epoch milliseconds when the challenge was created.
 */
data class Reto(
    val id: String = "",
    val descripcion: String = "",
    val createdAt: Long = System.currentTimeMillis()
) {
    /**
     * Converts this [Reto] to a plain [Map] suitable for Firestore persistence.
     */
    fun toFirestoreMap(): Map<String, Any> = mapOf(
        "id" to id,
        "descripcion" to descripcion,
        "createdAt" to createdAt
    )
}
